apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-web-deployment-namespace
  namespace: marketing
  labels: 
    app: content-web-service-mapping
    type: content-web-rs
spec:
  template:
    metadata:
      name: content-web-pod
      labels: 
        app: content-web-service-mapping
        type: content-web-service
    spec:
      containers:
      - name: content-web-pod
        image: myacrlab16284.azurecr.us/content-web:1.0-amd64
        ports:
        - containerPort: 3000
        env:
        - name: CONTENT_API_URL
          value: "http://content-api:3001"         
  replicas: 3 
  selector:
   matchLabels:
      type: content-web-service

 
 
        