apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api
  labels:
    app: content-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: content-api
  template:
    metadata:
      labels:
        app: content-api
    spec:
      containers:
      - name: content-api
        image: myacrlab16284.azurecr.us/content-api:1.0-amd64
        resources:
          requests:
            cpu: 500m
            memory: 128Mi
        ports:
        - containerPort: 3001

 
        