# Use the official Nginx image as the base image
# nginx: The NGINX web server — a popular, high-performance server 
# used for serving web apps, reverse proxying, and load balancing


#Nginx=The NGINX web server — a popular, high-performance server used for 
#serving web apps, reverse proxying, and load balancingalpineBuilt 

#Alpine Linux — an ultra-lightweight Linux distro (~5MB) instead of the 
#default Debian/Ubuntu base

FROM nginx:alpine

# Copy the static HTML page to Nginx's default static content directory

COPY index.html /usr/share/nginx/html/index.html


