apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-web-deployment
  labels: 
    app: content-web-service-mapping
    type: content-web-rs
spec:
  template:
    metadata:
      name: content-web-pod
      labels: 
        app: content-web-service-mapping
        type: content-web-service
    spec:
      containers:
      - name: content-web-pod
        image: myacrlab16284.azurecr.us/content-web:1.0-amd64
        ports:
        - containerPort: 3000
  replicas: 3 
  selector:
   matchLabels:
      type: content-web-service



 
        