apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azure-pvc
spec:
  accessModes:
    - ReadWriteOnce            # Standard for disks
  storageClassName: my-custom-sc
  resources:
    requests:
      storage: 5Gi             # Size requested
# pvc-d42535b2-bbf4-46b8-8341-6e0131dfe1d9

